services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: noteflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  ai-service:
    build:
      context: ./ai-service
    env_file:
      - ./ai-service/.env.development
    ports:
      - "8000:8000"

  api:
    build:  
      context: ./api
    env_file:
      - ./api/.env.development
    ports:
      - "5000:5000"
    depends_on:
      - db
      - ai-service

volumes:
  db_data: